### PR TITLE
fix(AwesomePrint): Replace with amazing_print

### LINKED ISSUE #27: Replace awesome_print with amazing_print
With Ruby 2.7.1, `awesome_print` emits a [deprecation warning](https://github.com/awesome-print/awesome_print/issues/382) when evaluating the Pry prompt:

```
2.7.1 (jazz_fingers)[5] » Array([3])
~/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/formatters/base_formatter.rb:113: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
~/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:63: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

It looks like `awesome_print` is abandoned but [there's a maintained fork](https://github.com/awesome-print/awesome_print/issues/382#issuecomment-653524820) it can be replaced with: https://github.com/amazing-print/amazing_print

### PR DESCRIPTION
**Pull request by h35514n**
AwesomePrint is stale and no longer maintained. This patch replaces it with AmazingPrint, a maintained fork. 

```
2.7.1 (jazz_fingers)[5] » Array([3])
~/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/formatters/base_formatter.rb:113: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
~/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:63: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

### After:

```
2.7.1 (jazz_fingers)[1] » Array(3)
=> [
    [0] 3
]
```

Fixes #27

### CODE REVIEW

File: lib/jazz_fingers/amazing_print.rb [hunk 1]
```diff
@@ -1,22 +1,22 @@
 module JazzFingers
-  AWESOME_PRINT = {
+  AMAZING_PRINT = {
     indent: 2,
     sort_keys: true,
     color: {
       args: :greenish,
-      array: :pale,
+      array: :whiteish,
       bigdecimal: :blue,
```
Comment (h35514n) [inline lib/jazz_fingers/amazing_print.rb:8]: `:pale` is [unsupported](https://github.com/amazing-print/amazing_print#usage) — changed to `:whiteish`

**Comment by plribeiro3000** [comment]
Looking good @jmromer. Thanks!

**Comment by plribeiro3000** [comment]
Released as `6.0.0.pre.rc1`
