### PR TITLE
Fix prompt-setting deprecation

### LINKED ISSUE #22: Deprecated setting prompt via an array of two procs
https://github.com/pry/pry/blob/master/CHANGELOG.md#deprecations
https://www.rubydoc.info/gems/pry/Pry/Prompt

I believe that's what's happening here:
https://github.com/plribeiro3000/jazz_fingers/blob/a89eb47055e861ca864c3d87baa7ad4618224999/lib/jazz_fingers.rb#L49
https://github.com/plribeiro3000/jazz_fingers/blob/a89eb47055e861ca864c3d87baa7ad4618224999/lib/jazz_fingers.rb#L24-L32
https://github.com/plribeiro3000/jazz_fingers/blob/a89eb47055e861ca864c3d87baa7ad4618224999/lib/jazz_fingers/prompt.rb#L71-L73

### PR DESCRIPTION
**Pull request by h35514n**
As of Pry v0.13.0, a [deprecation](https://github.com/pry/pry/blob/master/CHANGELOG.md#deprecations) warning is issued due to the way jazz_fingers sets the Pry prompt (see: https://github.com/pry/pry/pull/1877 and #22).

The change in 594223d appears to be all that's required to fix the deprecation minimally.

Commit beaadf4 refactors to use the approach suggested by Pry. The main benefit of this change is that adding the jazz fingers prompt to the `Pry::Prompt` hash allows for switching the
prompt dynamically from the Pry command line using `change-prompt jazz_fingers`.

<details>
<summary>changing the prompt with <code>change-prompt</code></summary>

```rb
2.7.0 (jazz_fingers)[1] » change-prompt --list
# default
# The default Pry prompt. Includes information about the current expression
# number, evaluation context, and nesting level, plus a reminder that you're
# using Pry.
# 
# simple
# A simple `>>`.
# 
# nav
# A prompt that displays the binding stack as a path and includes information
# about _in_ and _out_.
# 
# shell
# A prompt that displays `$PWD` as you change it.
# 
# none
# Wave goodbye to the Pry prompt.
# 
# jazz_fingers (selected)
# JazzFingers prompt

2.7.0 (jazz_fingers)[2] » change-prompt default

[3] pry(main)> change-prompt simple

>> change-prompt jazz_fingers

2.7.0 (jazz_fingers)[5] »
```
</details>

The convenience afforded by `Pry::Prompt.add` also made it easy to add support for displaying the local context (examples below), so that's included in beaadf4 as well.

```rb
2.5.5 (jazz_fingers)[1] » cd Class1::Class2::Class3::Class4
2.5.5 (Class1::Class2::Class3::Class4)[2] »
```

Commit 2453e7e abbreviates object paths displayed in object instances, which can get very long  in the context of test runs:

```
    1559:         require "pry"; binding.pry
 => 1560:         bike.set_location_info
    1561: 

2.5.5 (#<RSpec::ExampleGroups::Bike::SetLocationInfo::GivenNoCreationOrgLocation>)[1] » 
```

The abbreviation is performed by taking as much of the tail of the object path entries list as possible, subject to a max character count constraint. 

An example (Given a `binding.pry` in `Class10#some_method`):

```rb
2.5.5 (jazz_fingers)[4] » Class1::Class2::Class3::Class4::Class5::Class6::Class7::Class8::Class9::Class10.new.some_method
2.5.5 (#<...Class7::Class8::Class9::Class10>)[1] » exit
```

Alternatively, another way to abbreviate the context string for object instances is to only include the root and leaf nodes in the object path (this isn't currently implemented, but can be added with a couple of lines):

```rb
2.7.0 (#<Class1::...::Class10>)[1] » 
```
Happy to modify any of the above as desired.

Fixes #22

### CODE REVIEW

File: lib/jazz_fingers/prompt.rb [hunk 1]
```diff
@@ -32,44 +34,55 @@ def separator
...
-        "[#{bold_text(pry.input_ring.size)}]"
+        bold_text(pry.input_ring.size)
       else
-        "[#{bold_text(pry.input_array.size)}]"
+        bold_text(pry.input_array.size)
       end
     end
 
-    def text(object, level)
-      level = 0 if level < 0
```
Comment (h35514n) [inline lib/jazz_fingers/prompt.rb:48]: This method (`#text`) doesn't appear to be used anywhere, so I removed it — let me know if I should revert this change.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,10 @@
 # CHANGELOG
 
+## 5.0.2 (unreleased)
+* Use non-deprecated method of setting prompt (see [Pry PR #1877][pry-1877])
+
+[pry-1877]: https://github.com/pry/pry/pull/1877
+
```
Comment (plribeiro3000) [inline CHANGELOG.md]: Could you leave this to be done in another commit/PR please?

File: jazz_fingers.gemspec [hunk 3]
```diff
@@ -21,7 +21,7 @@ Gem::Specification.new do |gem|
   # Dependencies
   gem.required_ruby_version = '>= 2.0'
   gem.add_runtime_dependency 'awesome_print', '~> 1.6'
-  gem.add_runtime_dependency 'pry', '~> 0.10'
+  gem.add_runtime_dependency 'pry', '>= 0.13.0'
```
Comment (plribeiro3000) [inline jazz_fingers.gemspec]: Hmmm. Does this mean that someone that can't use `pry >= 0.13.0` will have to keep using old version of `jazz_fingers`?

Maybe we can loose this a bit and work on the code to work on both constraints?

File: lib/jazz_fingers.rb [hunk 4]
```diff
@@ -28,7 +28,24 @@ def prompt
...
+
+      Pry::Prompt.add(
+        :jazz_fingers,
+        "A spruced-up prompt provided by jazz_fingers.",
+        prompt.separators
+      ) do |context, _nesting, pry, separator|
+        prompt.template(Pry.view_clip(context), pry, separator)
+      end
+
+      Pry::Prompt[:jazz_fingers]
```
Comment (plribeiro3000) [inline lib/jazz_fingers.rb]: What if we make this in the `Prompt` class instead?

There is a lot more going on on the `prompt` front then just `template(Pry.view_clip(context), pry, separator)`.

What if the `Prompt` class becomes responsible to add itself to `Pry::Prompt`?

File: lib/jazz_fingers/configuration.rb [hunk 5]
```diff
@@ -39,10 +39,10 @@ def awesome_print?
     end
 
     def application_name
-      return "(#{underscore(@application_name)})" unless @application_name.nil?
-      return "(#{Rails.application.class.parent_name.underscore})" if defined?(Rails)
+      return underscore(@application_name) unless @application_name.nil?
+      return Rails.application.class.parent_name.underscore if defined?(Rails)
```
Comment (plribeiro3000) [inline lib/jazz_fingers/configuration.rb:43]: I like to have `()` around the project name to have a separated context.

Why the change?

File: lib/jazz_fingers/prompt.rb [hunk 6]
```diff
@@ -32,44 +34,67 @@ def separator
...
+        case module_name
+        when "main", "nil"
+          @application_name
+        when OBJECT_INSTANCE
+          abbreviated_context(module_name)
+        else
+          module_name
+        end
+
+      blue_text("(#{name})")
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb:72]: Not sure i follow everything here but i guess once we figure out the other stuff i commented we can follow here.

File: lib/jazz_fingers/version.rb [hunk 7]
```diff
@@ -1,3 +1,3 @@
 module JazzFingers
-  VERSION = '5.0.1'.freeze
+  VERSION = "5.0.2".freeze
```
Comment (plribeiro3000) [inline lib/jazz_fingers/version.rb]: Please don't do this in the same commit/PR.

File: CHANGELOG.md (hunk 2 above)
Comment (h35514n) [reply CHANGELOG.md]: No prob - updated in b54e2e6

File: lib/jazz_fingers/configuration.rb (hunk 5 above)
Comment (h35514n) [reply lib/jazz_fingers/configuration.rb:43]: There's no change in behavior / prompt formatting — the parentheses are just moved to the prompt class to reduce duplication:

```rb
# lib/jazz_fingers/prompt.rb L48-49 (2453e7e2)

  blue_text("(#{name})")
end
```
<sup>[[source](https://github.com/jmromer/jazz_fingers/blob/2453e7e2/lib/jazz_fingers/prompt.rb#L48-L49)]</sup>

File: lib/jazz_fingers.rb (hunk 4 above)
Comment (h35514n) [reply lib/jazz_fingers.rb]: > There is a lot more going on on the prompt front then just template(Pry.view_clip(context), pry, separator)

Can you disambiguate? I'm not sure what you mean by this.

> What if we make this in the Prompt class instead?

That's possible (that would be similar to 594223d). The current approach takes the `JazzFingers` module as the integration point with `Pry`, so the hard dependency on the `Pry` class is isolated there.

File: lib/jazz_fingers/prompt.rb (hunk 6 above)
Comment (h35514n) [reply lib/jazz_fingers/prompt.rb:72]: Good call-out thanks — I added some documentation in 4b815c7

File: jazz_fingers.gemspec (hunk 3 above)
Comment (h35514n) [reply jazz_fingers.gemspec]: Makes sense. I'm taking a look at that now. Seems like the current Pry dependency requirement might be incorrect? I'm trying to find the most recent Pry version number that works with the currently release jazz_fingers 5.0.1...

```rb
[8] pry(main)> JazzFingers::VERSION
# => "5.0.1"
[9] pry(main)> Pry::VERSION
# => "0.10.0"

[5] pry(main)> JazzFingers
# => JazzFingers

[6] pry(main)> JazzFingers.configure
# NoMethodError: undefined method `configure' for JazzFingers:Module

[7] pry(main)> JazzFingers.setup!
# NoMethodError: undefined method `setup!' for JazzFingers:Module
```

Safe to ignore — `gem` was sourcing the modified version of 5.0.1 from the local cache instead of re-downloading it.

```rb
2.5.5 (jazz_fingers)[1] » Pry::VERSION
# "0.10.0"
2.5.5 (jazz_fingers)[2] » JazzFingers::VERSION
# "5.0.1"
2.5.5 (jazz_fingers)[3] » JazzFingers.setup!
# => true
```

Comment (h35514n) [reply jazz_fingers.gemspec]: Commit 857320f restores backwards-compatibility down to Pry ~> 0.10

85c5e86 refactors to isolate branching and move special casing to a different class — if that's too design-y or if you'd prefer a different class name, let me know.

```rb
# lib/jazz_fingers.rb L25-40 (85c5e865)

def prompt_class
  if Pry::VERSION >= "0.13.0"
    PromptPry013
  else
    PromptPry012
  end
end

def prompt
  @prompt ||=
    prompt_class.new(
      colored: config.colored_prompt,
      separator: config.prompt_separator,
      application_name: config.application_name
    )
end
```
<sup>[[source](https://github.com/jmromer/jazz_fingers/blob/85c5e865/lib/jazz_fingers.rb#L25-L40)]</sup>

Comment (h35514n) [reply jazz_fingers.gemspec]: Btw an alternative here would be to mix-in functionality by target pry version rather than inherit:

```rb
class Prompt
  if Pry::VERSION >= "0.13.0"
    include PromptPry013
  else
    include PromptPry012
  end
   # . . . 
end
```

Comment (h35514n) [reply jazz_fingers.gemspec]: Here's what that looks like: d2f71b3
Happy to keep either approach or change tack altogether.

Tested on pry 0.10.0 and 0.13.1:

```rb
2.5.5 (jazz_fingers)[1] » JazzFingers::VERSION
"5.0.1"

2.5.5 (jazz_fingers)[2] » Pry::VERSION
"0.10.0"
```

```rb

2.7.0 (jazz_fingers)[1] » JazzFingers::VERSION
"5.0.1"

2.7.0 (jazz_fingers)[2] » Pry::VERSION
"0.13.1"
```

File: lib/jazz_fingers/prompt.rb [hunk 8]
```diff
@@ -28,48 +38,81 @@ def bold_text(text)
...
-    def separator
+    def main_separator
       red_text(@separator)
     end
 
-    def name
-      blue_text(@application_name)
+    def wait_separator
+      "*"
+    end
```
Comment (h35514n) [inline lib/jazz_fingers/prompt.rb:49]: The naming here is updated for consistency with [Pry's](https://github.com/pry/pry/wiki/Customization-and-configuration#the-prompt) nomenclature:

> Pry can accept two prompt-types for every prompt - the 'main prompt' and the 'wait prompt'. The main prompt is always used for the first line of input; the wait prompt is used in multi-line input to indicate that the current expression is incomplete and more lines of input are required.

File: lib/jazz_fingers/prompt/pry_012.rb [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+        [main_prompt, wait_prompt]
+      end
+
+      def main_prompt
+        lambda do |context, _nesting, pry|
+          template(Pry.view_clip(context), pry, main_separator)
+        end
+      end
+
+      def wait_prompt
```
Comment (h35514n) [inline lib/jazz_fingers/prompt/pry_012.rb]: see: https://github.com/plribeiro3000/jazz_fingers/pull/23/files#r408413403

**Comment by aried3r** [comment]
This looks great! Thanks for taking the time and putting so much effort into it. @plribeiro3000, WDYT?

File: lib/jazz_fingers/configuration.rb (hunk 5 above)
Comment (plribeiro3000) [reply lib/jazz_fingers/configuration.rb:43]: Ohhh. Cool

File: lib/jazz_fingers/prompt.rb (hunk 8 above)
Comment (plribeiro3000) [reply lib/jazz_fingers/prompt.rb:49]: 👍

File: lib/jazz_fingers/prompt.rb [hunk 10]
```diff
@@ -1,5 +1,18 @@
+# frozen_string_literal: true
+
+require_relative "prompt/pry_012"
+require_relative "prompt/pry_013"
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: I rather use `autoload` here.

This way we won't load code that is not going to be used.

File: lib/jazz_fingers/prompt.rb [hunk 11]
```diff
@@ -1,5 +1,18 @@
...
+
 module JazzFingers
   class Prompt
+    OBJECT_INSTANCE = /#<(.+)>/
+
+    if Pry::VERSION >= "0.13.0"
+      include Pry013
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: Maybe call this `Pry::Prompt::UnderVersion013` and `Pry::Prompt::AboveVersion012`?

Just a thought. I usually prefer names with more context. It makes easier for someone that is not aware of everything happening to debug it when/if needed.

WDYT?

File: lib/jazz_fingers/prompt.rb [hunk 12]
```diff
@@ -28,48 +41,81 @@ def bold_text(text)
...
+      "*"
+    end
+
+    # Return the current Pry context
+    #
+    # When the Pry context is `"main"` or `"nil"`, use the application name from
+    # the JazzFingers config. Examples: "(my_rails_app_name)", "(jazz_fingers)".
+    #
+    # When in the context of an object instance, use the abbreviated object
+    # path. Example: "(#<Pry::Prompt>)", "(#<...::ModuleName::ClassName>)"
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: COOOOOOOOOOL!

👏 👏 👏 👏

File: lib/jazz_fingers/prompt.rb [hunk 13]
```diff
@@ -28,48 +41,81 @@ def bold_text(text)
...
       end
-    end
 
-    def block_prompt
-      lambda do |_object, level, pry|
-        spaces = '  ' * level
-        "#{RUBY_VERSION} #{name}#{line_number(pry)} * #{spaces}"
-      end
+      ["#<...", tail.join("::"), ">"].join
     end
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb:102]: Now that i understand what this method does i'm a bit worried that its complexity might add some bugs.

I have some concerns here that if two difficult to address maybe we could try to test it out? Lets see if we can make this code a bit simplier.

PS: I know is harsh to test it. Thats one of the main reasons it does not have tests at all but i tried as much as possible to keep it simple so the necessity would not be too big.

File: lib/jazz_fingers/prompt.rb [hunk 14]
```diff
@@ -28,48 +41,81 @@ def bold_text(text)
...
+      object_path_components = object_path.split("::")
+      return object_label if object_path_components.length == 1
 
-      if text == 'main'
-        ''
-      else
-        "(#{'../' * level}#{text})"
-      end
-    end
+      object_path_length = object_path_components.map(&:length).sum
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: Wouldn't the right length be based on object_path instead?
This result does not account fot `::`.

File: lib/jazz_fingers/prompt.rb [hunk 15]
```diff
@@ -28,48 +41,81 @@ def bold_text(text)
...
+      return object_label if object_path_length < max_length
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: If we follow my last comment i believe this should be the first guard clause on this method.

File: lib/jazz_fingers/prompt.rb [hunk 16]
```diff
@@ -28,48 +41,81 @@ def bold_text(text)
...
+        (object_path_length -= component.length) > max_length
       end
-    end
 
-    def block_prompt
-      lambda do |_object, level, pry|
-        spaces = '  ' * level
-        "#{RUBY_VERSION} #{name}#{line_number(pry)} * #{spaces}"
-      end
+      ["#<...", tail.join("::"), ">"].join
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: Food for thought.

What if we just change this all together to always show the first and last module/class?

This way we won't loose the Root element neither the last one.

WDYT?

**Comment by plribeiro3000** [comment]
@jmromer I gotta say.

This has been a hell out of a good job understanding how `pry` works and how to make this change in a good way.

Than you a ton for your relentless efforts here. This feature will make it way much better.

❤️ ❤️ ❤️ ❤️ ❤️

File: lib/jazz_fingers/prompt.rb [hunk 17]
```diff
@@ -28,48 +41,81 @@ def bold_text(text)
...
+    # Examples:
+    #   In:  #<Class1::Class2::Class3::Class4::Class5>
+    #   Out: #<...Class2::Class3::Class4::Class5>
+    #
+    #   In:  #<Class1::Class2>
+    #   Out: #<Class1::Class2>
+    #
+    #   In:  #<NoPathJustASingleLongClassName>
+    #   Out: #<NoPathJustASingleLongClassName>
+    def abbreviated_context(object_label, max_length: 20)
```
Comment (plribeiro3000) [inline lib/jazz_fingers/prompt.rb]: Hmmmmm. Could we make `max_length` configurable?

File: lib/jazz_fingers/prompt.rb (hunk 14 above)
Comment (h35514n) [reply lib/jazz_fingers/prompt.rb]: Accounting for the colons adds complexity to the subsequent iteration.
But: Only showing the root and leaf will be easier to maintain, so I'll pivot toward that instead. Updated in a7208be

File: lib/jazz_fingers/prompt.rb (hunk 16 above)
Comment (h35514n) [reply lib/jazz_fingers/prompt.rb]: That works! simpler to maintain. Updated in a7208be

File: lib/jazz_fingers/prompt.rb (hunk 10 above)
Comment (h35514n) [reply lib/jazz_fingers/prompt.rb]: Using autoload for these modules creates an exception when running Pry in a Bundler context: https://github.com/plribeiro3000/jazz_fingers/pull/23/commits/ea6633bfea4ea68d7ba6855d57ba9b8a062ed718

I think these lines will only be triggered when `JazzFingers::Prompt` is autoloaded, but if there's another way you'd recommend I can test it out.

File: lib/jazz_fingers/prompt.rb (hunk 11 above)
Comment (h35514n) [reply lib/jazz_fingers/prompt.rb]: Sounds good — updated in 4e0e5ff

**Comment by plribeiro3000** [comment]
Great work here @jmromer.

Sorry for the delays to review.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by plribeiro3000** [comment]
Just released as `5.1.0.rc1`.

Will try it out in my projects and see if everything works ok.
